<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <IsPublishable>false</IsPublishable>
  </PropertyGroup>

	<ItemGroup>
	   <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\SmartDiscount.IntegrationEventLogEF\SmartDiscount.IntegrationEventLogEF.csproj" />
    <ProjectReference Include="..\SmartDiscount.Ordering.Domain\SmartDiscount.Ordering.Domain.csproj" />
  </ItemGroup>

</Project>
