syntax = "proto3";

option csharp_namespace = "SmartDiscount.Basket.API.Grpc";

package SmartDiscount.Basket.API;

service Basket {
    rpc GetBasket(GetBasketRequest) returns (CustomerBasketResponse) {}
    rpc UpdateBasket(UpdateBasketRequest) returns (CustomerBasketResponse) {}
    rpc DeleteBasket(DeleteBasketRequest) returns (DeleteBasketResponse) {}
}

message GetBasketRequest {
}

message CustomerBasketResponse {
    repeated BasketItem items = 1;
    string promo_code = 2;           
    double discount_amount = 3;      
}

message BasketItem {
    int32 product_id = 2;
    int32 quantity = 6;
}

message UpdateBasketRequest {
    repeated BasketItem items = 2;
    string promo_code = 3;           
    double discount_amount = 4;  
}

message DeleteBasketRequest {
}

message DeleteBasketResponse {
}