<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>SmartDiscount.WebApp</RootNamespace>
		<!-- Disable RZ10021, which is failing due to a Razor bug, according to Mackinnon. -->
		<NoWarn>$(NoWarn);RZ10021</NoWarn>
	</PropertyGroup>

	<ItemGroup>
        <ProjectReference Include="..\SmartDiscount.EventBusServiceBus\SmartDiscount.EventBusServiceBus.csproj" />
		<ProjectReference Include="..\SmartDiscount.ServiceDefaults\SmartDiscount.ServiceDefaults.csproj" />
		<ProjectReference Include="..\SmartDiscount.WebAppComponents\SmartDiscount.WebAppComponents.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http.Client" />
		<PackageReference Include="Aspire.Azure.AI.OpenAI" />
		<PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.ClientFactory" />
		<PackageReference Include="Grpc.Tools" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\SmartDiscount.Basket.API\Proto\basket.proto" GrpcServices="Client" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\images\" />
	</ItemGroup>

</Project>
