<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\SmartDiscount.EventBusServiceBus\SmartDiscount.EventBusServiceBus.csproj" />
    <ProjectReference Include="..\SmartDiscount.ServiceDefaults\SmartDiscount.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
