<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>SmartDiscount.WebAppComponents</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Catalog\CatalogSearch.razor.css~RFcf5fae88.TMP" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

</Project>
