<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <RootNamespace>SmartDiscount.IntegrationEventLogEF</RootNamespace>
	  <IsPublishable>false</IsPublishable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SmartDiscount.EventBus\SmartDiscount.EventBus.csproj" />
	</ItemGroup>
	
</Project>
